/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package us.navonod.playground;

import java.io.IOException;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws IOException {
        String fileName = args[0];

        Transposer transposer = new Transposer();
        System.out.println(transposer.readFile(fileName));
    }
}
